<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="USHYDIVENUGOP06" failures="1" tests="1" name="Add Customer test" time="7.609" errors="0" timestamp="2021-05-17T22:43:06 IST">
  <testcase classname="com.w2a.testCases.AddingUsersTest" name="AddUsers" time="5.344">
    <failure type="java.lang.AssertionError" message="Failing after  Adding user test)">
      <![CDATA[java.lang.AssertionError: Failing after  Adding user test)
at com.w2a.testCases.AddingUsersTest.AddUsers(AddingUsersTest.java:37)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- AddUsers -->
</testsuite> <!-- Add Customer test -->
