<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="USHYDIVENUGOP06" failures="1" tests="1" name="LoginTest" time="4.079" errors="0" timestamp="2021-05-17T22:42:59 IST">
  <testcase classname="com.w2a.testCases.LoginTest" name="loginAsBankManager" time="3.26">
    <failure type="java.lang.AssertionError" message="Failing after  login test)">
      <![CDATA[java.lang.AssertionError: Failing after  login test)
at com.w2a.testCases.LoginTest.loginAsBankManager(LoginTest.java:29)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- loginAsBankManager -->
</testsuite> <!-- LoginTest -->
